add network driver based on the Virtio Over MMIO
hermitcore/libhermit-rs pull request #296
Opened 2021-11-20 16:48 UTC by stlankes

Base on the work of @duanyu-yu, we developed a network driver based on the Virtio Over MMIO interface, which is part of the Virtual I/O Device Specification. Details are published at https://docs.oasis-open.org/virtio/virtio/v1.1/csprd01/virtio-v1.1-csprd01.html
    
This network driver doesn't depend on the PCI bus and can be used within micro VMs. The current version is developed and tested on Qemu's microvm virtual platform. Details are published at https://qemu.readthedocs.io/en/latest/system/i386/microvm.html
    
The current version can be tested with the example web server of RustyHermit's Git repository. Please use following command to build the web server:
    
> cargo build --no-default-features --features smoltcp -p httpd
    
Afterwards, the following command starts the web server withinthe microvm:
    
> qemu-system-x86_64 -M microvm,x-option-roms=off,pit=off,pic=off,rtc=on,auto-kernel-cmdline=off -global virtio-mmio.force-legacy=off -nodefaults -no-user-config -display none -smp 1 -m 1G -serial stdio -kernel loader/target/x86_64-unknown-hermit-loader/debug/rusty-loader -initrd target/x86_64-unknown-hermit/debug/httpd -enable-kvm -cpu host -device isa-debug-exit,iobase=0xf4,iosize=0x04 -netdev tap,id=tap10,ifname=tap10,script=no,downscript=no -device virtio-net-device,netdev=tap10

2021-11-26 15:53 UTC, mkroening commented on src/arch/x86_64/kernel/mmio.rs
> +
```suggestion
```

And add Yu Duan to `authors` in `Cargo.toml`.

2021-11-28 11:17 UTC, mkroening requested changes
I found a few more copyright headers from Frederik Schulz and you, @stlankes.

I did not review the code in detail but in general this looks good to me.

r=me when copyright headers are gone.

2021-11-28 11:17 UTC, mkroening commented on src/drivers/net/virtio_mmio.rs
> +
```suggestion
```

2021-11-28 11:17 UTC, mkroening commented on src/drivers/net/virtio_pci.rs
> +
```suggestion
```

2021-11-28 11:17 UTC, mkroening commented on src/drivers/virtio/transport/mmio.rs
> +
```suggestion
```

2021-11-28 12:18 UTC, stlankes commented
r=me

2021-11-28 12:48 UTC, mkroening approved these changes
bors r+

2021-11-28 13:09 UTC, merged