Restore network configuration via kernel cli
hermitcore/libhermit-rs pull request #571
Opened 2022-11-09 10:17 UTC by JTS22

Restores the ability to set the network IP address, gateway and subnet mask via the kernel commandline arguments `-ip`, `-gateway` and `-mask`.

Closes #522

2022-11-09 11:06 UTC, mkroening requested changes
Thanks for your PR! :)

It would be good to introduce an `fn var(key: &str) -> Option<String>` in `env` akin to [`std::env::var`](https://doc.rust-lang.org/nightly/std/env/fn.var.html).

The variables could then be defined with macros and with less redundancy, similar to how it was before https://github.com/hermitcore/libhermit-rs/commit/eb2a46fe4d2892957a7e31fd8ce60bcd21a78f52.

If you would rather have me do these changes, just say so.

Also, please squash your commits in the end. :)

2022-11-09 12:02 UTC, JTS22 commented
I agree that would make sense, I will try to implement that :)

2022-11-10 15:00 UTC, mkroening requested changes
Looks great! Just two minor suggestions.

2022-11-10 15:12 UTC, JTS22 commented on src/syscalls/interfaces/mod.rs
> +			let ptr = Box::leak(format!("{}={}\0", a.0, a.1).into_boxed_str()).as_ptr();
Done

2022-11-10 15:13 UTC, JTS22 commented on src/env.rs
> +#[allow(dead_code)]
Changed it, though clippy does not seem to like it...

2022-11-10 15:19 UTC, mkroening commented on src/env.rs
> +#[allow(dead_code)]
Ah, yes. Looking at it more closely, it should be `cfg(all(feature = "tcp", not(feature = "dhcpv4")))`, I think.

2022-11-10 15:21 UTC, JTS22 commented on src/env.rs
> +#[allow(dead_code)]
Yes, that works :)

2022-11-10 15:32 UTC, merged