Implements PriorityTaskQueue with std's LinkedList rather than a custom linked list implementation
hermitcore/libhermit-rs pull request #706
Opened 2023-04-12 01:50 UTC by michaelRichards99

Fixes https://github.com/hermitcore/libhermit-rs/issues/377.

2023-04-14 06:50 UTC, stlankes commented
Looks good! But I will discuss it with @mkroening Just a double check.

2023-04-16 18:58 UTC, mkroening requested changes
This looks good! Thanks a lot!

Two minor remarks, though the current code is definitely an improvement already. 👍

2023-04-16 18:58 UTC, mkroening commented on src/scheduler/task.rs
> +			if handle.id == current_task.borrow().id {
This could be simplified by using `Iterator::find`.

2023-04-16 18:58 UTC, mkroening commented on src/scheduler/task.rs
> +				self.queues[i].append(&mut split_list);
We might want to extract this code into a function (be it inline or outside this method) for clarity.

2023-04-18 03:13 UTC, michaelRichards99 commented
Thank you for the feedback :). We've addressed those 2 changes and made sure the priority bitmap is properly set when removing a task from a list. 

Thank you @ynchen2829 for authoring these changes.

2023-04-18 06:31 UTC, mkroening approved these changes
Looks good to me!

Thanks a lot! :)

bors r+

2023-04-18 06:31 UTC, mkroening commented on src/scheduler/task.rs
> +	fn remove_from_queue(
Ah, nice! You even made this a fully fledged method. 👍

2023-04-18 06:38 UTC, merged